name: JustAnimations
version: 1.0.0 SNAPSHOT
main: com.imjustdoom.justanimations.JustAnimations
api-version: 1.18
authors: [ JustDoom ]
softdepend:
  - WorldEdit
commands:
  justanimations:
    aliases: [ ja, justanimations ]
    permission-message: "You do not have permission to use this command noob"
permissions:
  justanimations.admin:
    default: op